version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    hostname: clickhouse
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
    volumes:
      - ./config/config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=guardian
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    networks:
      - clickhouse-network

  data-loader:
    image: python:3.11
    container_name: data-loader
    depends_on:
      - clickhouse
    volumes:
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt
      - ./data-loader-logs:/app/logs
    working_dir: /app
    environment:
      - CLICKHOUSE_HOST=clickhouse # <-- use service name, not external IP
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DATABASE=guardian
    networks:
      - clickhouse-network
    command: >
      bash -c "
        pip install -r requirements.txt &&
        apt-get update && apt-get install -y cron &&
        echo '*/5 * * * * cd /app && python3 scripts/update_database_from_docker.py >> logs/cron.log 2>&1' > /etc/cron.d/data-loader &&
        chmod 0644 /etc/cron.d/data-loader &&
        crontab /etc/cron.d/data-loader &&
        cron -f
      "
    restart: unless-stopped

  fastapi:
    build: .
    container_name: fastapi-app
    depends_on:
      - clickhouse
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DATABASE=guardian
    ports:
      - "8000:80"
    volumes:
      - .:/app
    networks:
      - clickhouse-network
    restart: unless-stopped

networks:
  clickhouse-network:
    driver: bridge

volumes:
  clickhouse-data:
  clickhouse-logs:
