services:
  langchain:
    build:
      context: ../..
      dockerfile: services/streamlit/Dockerfile
    container_name: rag-langchain
    command: uvicorn llm_utils.langchain_controller:app --host 0.0.0.0 --port 8002
    ports:
      - 8002:8002
    volumes:
      - ../../.env:/app/.env
      - ../../llm:/app/
      - ./requirements.txt:/app/requirements.txt
      - ../../.streamlit:/app/.streamlit
    restart: unless-stopped
  ui:
    build:
      context: ../..
      dockerfile: services/streamlit/Dockerfile
    container_name: rag-langchain
    command: uvicorn llm_utils.langchain_controller:app --host 0.0.0.0 --port 8002
    ports:
      - 8002:8002
    volumes:
      - ../../.env:/app/.env
      - ../../llm:/app/
      - ./requirements.txt:/app/requirements.txt
      - ../../.streamlit:/app/.streamlit
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_FILTERS=resource-migrator=warn deletion-marker-migrator=warn
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    restart: unless-stopped
