services:
  ui:
    build:
      context: ../..  # or whatever root includes your langchain_ui.py
      dockerfile: services/streamlit/Dockerfile
    container_name: rag-ui
    ports:
      - 8501:8501
    volumes:
      - ../../.env:/app/.env
      - ../../llm:/app/llm
      - ./requirements.txt:/app/requirements.txt
      - ../../.streamlit:/app/.streamlit
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    restart: unless-stopped
