services:
  ui:
    build:
      context: ../..  # or whatever root includes your langchain_ui.py
      dockerfile: services/streamlit/Dockerfile
    container_name: rag-ui
    ports:
      - 8501:8501
    volumes:
      - ../../.env:/app/.env
      - ../../llm:/app/llm
      - ./requirements.txt:/app/requirements.txt
    restart: unless-stopped
